using System.Text.Json.Serialization;

namespace CtaClient.Models;

/// <summary>
///   Represents a single train arrival prediction generated by the CTA
/// </summary>
public class Arrival
{
    /// <summary>
    ///   Numeric GTFS parent station ID which this prediction is for.
    ///     Matches to "MapId" if provided in the request.
    /// </summary>
    [JsonPropertyName("staId")]
    public int StationId { get; set; }

    /// <summary>
    ///   Numeric GTFS stop ID which this prediction is for.
    /// </summary>
    [JsonPropertyName("stpId")]
    public int StopId { get; set; }

    /// <summary>
    ///   Proper name of the parent station
    /// </summary>
    [JsonPropertyName("staNm")]
    public string StationName { get; set; } = "";

    /// <summary>
    ///   Description of the platform for this prediction
    /// </summary>
    [JsonPropertyName("stpDe")]
    public string StopDescription { get; set; } = "";

    /// <summary>
    ///   Run number of the train in this arrival prediction
    /// </summary>
    [JsonPropertyName("rn")]
    public int RunNumber { get; set; }

    /// <summary>
    ///   Route name of the train in this arrival prediction
    /// </summary>
    [JsonPropertyName("rt")]
    public Route Route { get; set; }

    /// <summary>
    ///   GTFS unique stop ID where this train is expected to ultimately end its service run
    /// </summary>
    [JsonPropertyName("destSt")]
    public int DestinationStopId { get; set; }

    /// <summary>
    ///   Destination description
    /// </summary>
    [JsonPropertyName("destNm")]
    public string DestinationName { get; set; } = "";

    /// <summary>
    ///   Operational direction of the train, roughly corresponding to Northbound=1 and Southbound=5. See the
    ///     CTA documentation at https://www.transitchicago.com/developers/ttdocs/#_Toc296199910 for more info.
    /// </summary>
    [JsonPropertyName("trDr")]
    public int DirectionCode { get; set; }

    /// <summary>
    ///   Timestamp for when this arrival prediction was generated
    /// </summary>
    [JsonPropertyName("prdt")]
    public DateTimeOffset Timestamp { get; set; }

    /// <summary>
    ///   Timestamp for when this train is expected to arrive
    /// </summary>
    [JsonPropertyName("arrT")]
    public DateTimeOffset ArrivalTime { get; set; }

    /// <summary>
    ///   Flag indicating whether this train is now considered "Approaching" or "Due" for the selected station
    /// </summary>
    [JsonPropertyName("isApp")]
    public bool IsApproaching { get; set; }

    /// <summary>
    ///   Flag indicating whether this train is scheduled, in lieu of live data
    /// </summary>
    [JsonPropertyName("isSch")]
    public bool IsScheduled { get; set; }

    /// <summary>
    ///   Flag indicating whether a potential schedule fault has been detected.
    ///     See https://www.transitchicago.com/developers/ttdocs/#_Toc296199911 for more information on schedule faults.
    /// </summary>
    [JsonPropertyName("isFlt")]
    public bool IsFaulty { get; set; }

    /// <summary>
    ///   Flag indicating whether this train is considered "Delayed"
    /// </summary>
    [JsonPropertyName("isDly")]
    public bool IsDelayed { get; set; }

    /// <summary>
    ///   Flags (currently unused by the CTA)
    /// </summary>
    [JsonPropertyName("flags")]
    public string? Flags { get; set; } = null;

    /// <summary>
    ///   The current latitude position of this train, in decimal degrees
    /// </summary>
    [JsonPropertyName("lat")]
    public float? Latitude { get; set; }

    /// <summary>
    ///   The current longitude position of this train, in decimal degrees
    /// </summary>
    [JsonPropertyName("lon")]
    public float? Longitude { get; set; }

    /// <summary>
    ///   The current heading of this train, expressed in standard bearing degrees
    ///     (0 = North, 90 = East, 180 = South, and 270 = West. Range is 0 to 359, progressing clockwise)
    /// </summary>
    [JsonPropertyName("heading")]
    public int? Heading { get; set; }
}
